# Generated by Django 5.0.6 on 2024-05-20 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMesaServicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proNombre', models.CharField(db_comment='nombre del procedimiento', max_length=30, unique=True)),
                ('proDescripcion', models.TextField(db_comment='texto con la descripcion del procedimiento', max_length=1000)),
                ('FechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora del registro')),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solDescripcion', models.TextField(db_comment='texto de describe la solicitud del estado', max_length=1000)),
                ('FechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora del registro')),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion')),
                ('solOficinaAmbiente', models.ForeignKey(db_comment='hace referencia a la oficina o ambiente donde se encuentra el equipo', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.oficinaambinete')),
                ('solUsuario', models.ForeignKey(db_comment='hace referencia a el empleado que hace la solicitud', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casCodigo', models.CharField(db_comment='codigo unico del caso', max_length=20, unique=True)),
                ('casEstado', models.CharField(choices=[('solicitada', 'solicitada'), ('en proceso', 'en proceso'), ('finalizada', 'finalizada')], db_comment='eleccion del estado del caso', max_length=15)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion')),
                ('casUsuario', models.ForeignKey(db_comment='empleado del soporte tecnico asignado', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('casSolicitud', models.ForeignKey(db_comment='hace referencia a la solicitud', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.solicitudes')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solTipoSolucion', models.CharField(choices=[('parcial', 'parcial'), ('definitiva', 'definitiva')], db_comment='tipo de solucion, si es parcial o definitiva', max_length=20)),
                ('FechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora del registro')),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion')),
                ('solCaso', models.ForeignKey(db_comment='hace referencia al caso ', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.caso')),
                ('solProcedimiento', models.ForeignKey(db_comment='este es el procedimiento a realizar', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.tipoprocedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCasoTipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solSolucionCaso', models.ForeignKey(db_comment='hace referencia a la solucion del Caso', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.solucioncaso')),
                ('solTipoProcedimiento', models.ForeignKey(db_comment='hace referencia al tipo de la solucion', on_delete=django.db.models.deletion.PROTECT, to='AppMesaServicio.tipoprocedimiento')),
            ],
        ),
    ]
