# Generated by Django 4.2.13 on 2024-05-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMesaServicio', '0002_tipoprocedimiento_solicitudes_caso_solucioncaso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casUsuario',
            field=models.ForeignKey(db_comment='empleado del soporte tecnico asignado', default='solicitada', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
