# Generated by Django 4.2.13 on 2024-05-30 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMesaServicio', '0003_alter_caso_casusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casEstado',
            field=models.CharField(choices=[('solicitada', 'solicitada'), ('en proceso', 'en proceso'), ('finalizada', 'finalizada')], db_comment='eleccion del estado del caso', default='solicitada', max_length=15),
        ),
        migrations.AlterField(
            model_name='caso',
            name='casUsuario',
            field=models.ForeignKey(db_comment='empleado del soporte tecnico asignado', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
