# Generated by Django 4.2.13 on 2024-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMesaServicio', '0005_alter_solucioncaso_solprocedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='oficinaambinete',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='oficinaambinete',
            name='FechaHoraCreacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora del registro'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='FechaHoraCreacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora del registro'),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='FechaHoraCreacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora del registro'),
        ),
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='FechaHoraCreacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora del registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FechaHoraActualizacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FechaHoraCreacion',
            field=models.DateField(auto_now_add=True, db_comment='fecha y hora del registro'),
        ),
    ]
